# Generated by Django 3.2.5 on 2021-08-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('service', models.CharField(max_length=255, verbose_name='Serviço que realiza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('weight', models.FloatField(default=1, verbose_name='Peso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('telephone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('score', models.FloatField(default=0, verbose_name='Pontuação')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('local', models.CharField(max_length=255, verbose_name='Localidade')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('note', models.TextField(verbose_name='Observação')),
                ('r_factor', models.IntegerField(verbose_name='Fator R')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.team')),
                ('type_of_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.typeofrequest', verbose_name='Tipo de solcitiação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Data')),
                ('installations', models.IntegerField(verbose_name='Instalações')),
                ('detour', models.IntegerField(null=True, verbose_name='Desvio')),
                ('calculation_basis', models.IntegerField(default=5, verbose_name='Base do calculo')),
                ('justification', models.TextField(verbose_name='Justificativa')),
                ('technical', models.ManyToManyField(to='scheduling.Technician', verbose_name='Técnicos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Data')),
                ('current_balance', models.IntegerField(verbose_name='Saldo Atual')),
                ('open', models.IntegerField(verbose_name='Abertas')),
                ('completed', models.IntegerField(verbose_name='Concluídas')),
                ('previous_balance', models.IntegerField(verbose_name='Saldo Anterior')),
                ('type_of_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.typeofrequest', verbose_name='Tipo de solcitiação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentsDetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('detour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.detour')),
            ],
        ),
    ]
