# Generated by Django 3.2.5 on 2021-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentsdetour',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='detour',
            name='cause',
            field=models.TextField(verbose_name='Causa do atraso'),
        ),
    ]
