# Generated by Django 3.2.5 on 2021-08-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentsdetour',
            name='detour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scheduling.detour', verbose_name='anexos'),
        ),
        migrations.AlterField(
            model_name='attachmentsdetour',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
