# Generated by Django 3.2.5 on 2021-07-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20210722_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='detour',
            name='date',
            field=models.DateField(default='2021-07-23', verbose_name='Data'),
            preserve_default=False,
        ),
    ]
