# Generated by Django 3.2.5 on 2021-08-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20210826_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentsdetour',
            name='detour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scheduling.detour', verbose_name='Desvio'),
        ),
        migrations.AlterField(
            model_name='detour',
            name='cause',
            field=models.CharField(max_length=255, verbose_name='Causa do atraso'),
        ),
    ]
