# Generated by Django 3.2.5 on 2021-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_detour_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='telephone',
        ),
        migrations.AddField(
            model_name='technician',
            name='telephone',
            field=models.CharField(default='0000', max_length=255, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
