# Generated by Django 3.2.5 on 2021-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20210723_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='detour',
            name='detour',
            field=models.IntegerField(default=0, verbose_name='Desvio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detour',
            name='technical',
            field=models.ManyToManyField(to='scheduling.Technician', verbose_name='Técnicos'),
        ),
    ]
