# Generated by Django 3.2.5 on 2021-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20210802_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detour',
            name='detour',
            field=models.IntegerField(null=True, verbose_name='Desvio'),
        ),
    ]
