# Generated by Django 3.2.5 on 2021-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20210803_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='detour',
            name='calculation_basis',
            field=models.IntegerField(default=5, verbose_name='Base do calculo'),
        ),
        migrations.AlterField(
            model_name='typeofrequest',
            name='weight',
            field=models.FloatField(default=1, verbose_name='Peso'),
        ),
    ]
