# Generated by Django 3.2.5 on 2021-08-30 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0003_auto_20210826_1324'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data de registro')),
                ('protocol', models.IntegerField(primary_key=True, serialize=False, verbose_name='Protocolo de atendimento')),
                ('sent_to', models.CharField(choices=[('A', 'ENCAMINHADO PARA AGENDAMENTO'), ('F', 'ENCAMINHADO PARA FECHAMENTO'), ('AF', 'ENCAMINHADO PARA AGUARDANDO FECHAMENTO'), ('AC', 'ENCAMINHADO PARA AGUARDANDO CONTATO')], max_length=255)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_of_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.typeofrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
