# Generated by Django 3.2.5 on 2021-09-01 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_auto_20210831_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('district', models.CharField(max_length=255, verbose_name='Bairro')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('answer', models.CharField(max_length=255, verbose_name='Resposta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='sent_from',
            field=models.CharField(choices=[('AN', 'ANDAMENTO'), ('AC', 'AGUARDANDO CONTATO'), ('AF', 'AGUARDADO FECHAMENTO'), ('EA', 'EM ANALISE'), ('CH', 'CHAT')], max_length=255, null=True, verbose_name='Encaminhado de'),
        ),
        migrations.AlterField(
            model_name='register',
            name='sent_to',
            field=models.CharField(choices=[('AG', 'AGENDAMENTO'), ('F', 'FECHAMENTO'), ('AF', 'AGUARDANDO FECHAMENTO'), ('AC', 'AGUARDANDO CONTATO'), ('EA', 'EM ANALISE')], max_length=255, null=True, verbose_name='Encaminhado para'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameFlat', models.CharField(max_length=255, verbose_name='Nome do plano')),
                ('infrastructure', models.CharField(max_length=255, verbose_name='Infraestrutura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('note', models.TextField(verbose_name='Observação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.client')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.service'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
