# Generated by Django 3.2.5 on 2021-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20210901_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(max_length=255, verbose_name='Resposta'),
        ),
    ]
