# Generated by Django 3.2.5 on 2021-09-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_register_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(verbose_name='Resposta'),
        ),
    ]
