# Generated by Django 3.2.5 on 2021-09-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20210909_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.client', unique=True),
        ),
    ]
